#
# Agent configuration
#

#
# Interfaces to sniff
#
interfaces: [
  "Realtek PCIe GBE Family Controller #2",
  "Microsoft Wi-Fi Direct Virtual Adapter",
  "Microsoft Wi-Fi Direct Virtual Adapter #3",
  "Intel(R) Dual Band Wireless-AC 7265",
  "Bluetooth Device (Personal Area Network)",
]

#
# Cache aging setup
#
cache_limit: 1024
cache_active_timeout: 1800
cache_inactive_timeout: 15

#
# Collector parameters
#
collector_address: "127.0.0.1"
collector_port: 9999

#
# Share key for messages encryption
# Keep this secret, SECRET!
#
key: "raQHLAAWepWDA9rxUCH5sP-FEMnMZ419B4zO7YmyeMI="