#
# Collector configuration
#

bind_address: "127.0.0.1"
bind_port: 9999
writers_number: 5
processors_number: 5
token_ttl: 5

#
# Agents white list
# {Adesses:Fernet key,...}
#
# Keep the secrets, SECRET!
#
agents: {
  "127.0.0.1": "raQHLAAWepWDA9rxUCH5sP-FEMnMZ419B4zO7YmyeMI=",
  "127.0.0.2": "raQHLAAWepWDA9rxUCH5sP-FEMnMZ419B4zO7YmyeMI="
}

#
# Database (Sqlite 3)
#
db_name: "database/collector.db"

#
# Database (InfluxDB)
#
influx_user: "myason_admin"
influx_password: "zvxmhwfn"
influx_host: "192.168.1.8"
influx_port: "8086"
influx_dbname: "myason"